//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumento
    {
        public int id_Documento { get; set; }
        public System.DateTime Data { get; set; }
        public string Nome { get; set; }
        public string image { get; set; }
        public int tblUsuario_id_Usuario { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
